name: Docker Image CI

on:
  push:
    branches: [carbon]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20']
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Fetch Key
        run: |
          echo "${{ secrets.GO_MODULE_PRIVATE_KEY }}" > p_key
          mkdir -p ~/.ssh
          cp p_key ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config

      - name: run tests
        run: go test -json ./... > test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.3.0
        with:
          test-results: test.json
          package-name: foobar # optional, if using custom package name, github.com/owner/repo stripped from the pathname by default

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: DigitalOcean Docker Image Publish
        uses: ripplr-io/docr-docker-publish@v1
        with:
          image_path: ${{ secrets.IMAGE_PATH_CARBON }}
          sha_size: 8 # optional, default is 8

      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.chat }}
          token: ${{ secrets.token }}
          status: ${{ job.status }}

      - name: Clean Up
        run: rm p_key
